pipeline {
    agent { label 'slave-L1'}
    tools {
        maven 'Maven-3'
        jdk 'jdk17'
    }
    stages {
         stage('Compile') {
            steps {
                dir('Boardgame-main') {
                sh 'mvn compile'
                                      }
                 }
        }
         stage('Test') {
            steps {
                dir('Boardgame-main') {
                sh 'mvn test'
                                      }
                  }
        }
    }
}



// pipeline {
//     agent any
//     tools{
//         maven 'Maven-3'
//         jdk 'jdk17'
//     }
//     environment{
//         POM_FILE = 'Boardgame-main/pom.xml'
//     }
//     parameters{
//         string(name: 'BRANCH_NAME', defaultValue: 'main', description: 'Select Git branch to build')
//     }
//     stages {
//         stage('git checkout') {
//             steps {
//                 dir('Boardgame-main'){
//                 git branch: "${params.BRANCH_NAME}", url: 'https://github.com/msmp5187/Boardgame.git'
//                 }
//             }
//         }
//           stage('Maven compile') {
//             steps {
//                 dir('Boardgame-main'){
//                 sh 'mvn -f ${POM_FILE} clean package'
//                 }
//             }
//         }        
//     }
//     post{
//         success {
//              echo "✅ Build Successful"
//         }
//         failure {
//             echo "❌ Build Failed"
//         }
//         always{
//             echo "Job completed at ${new Date()} "
//         }
//         }
    
// }



============================================================================


//     pipeline {
//     agent any
//     parameters {
//         string(name: 'DEPLOY_ENV', defaultValue: 'DEV', description: 'SELECT ENV TO DEPLOY' )
//         booleanParam(name: 'RUN_TEST', defaultValue: 'true', description: 'Do you wann RUN_TESTS ?')
//     }
//     environment{
//         REGION = 'ap-south-1'
//         BUILD_VERSION = "1.0${env.BUILD_NUMBER}"
//     }
//     stages {
//         stage('Built In Parameters/variables') {
//             steps {
//                 echo "Job Name is ${env.JOB_NAME}"
//                 echo "Job Number is ${env.BUILD_NUMBER}"
//             }
//         }
//         stage('Pipeline Parameters/variables') {
//             steps {
//                 echo "Deployable Env is ${params.DEPLOY_ENV}"
//                 echo "RUN Tests ${params.RUN_TEST}"
//             }
//         }            
//         stage('Custom Parameters/variables') {
//             steps {
//                 echo "REGION IS ${env.REGION}"
//                 echo "BUILD_VERSION IS ${env.BUILD_VERSION}"
//             }
//         }    
//     }
// }

========================================================================================





    pipeline {
    agent any
    tools {
        maven "Maven-3"
        jdk "jdk17"
    }
    environment {
        POM_PATH = 'Boardgame-main/pom.xml'
        SCANNER_HOME = tool 'sonar-scanner'
    }
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/msmp5187/Jenkins.git'
            }
        }
    stage('Compile') {
            steps {
                sh 'mvn -f ${POM_PATH} clean compile'
            }
        }
    stage('Test') {
            steps {
                sh 'mvn -f ${POM_PATH} test'
            }
        }
    stage('Package') {
            steps {
                sh 'mvn -f ${POM_PATH} package'
            }
        }
    stage('Sonarqube-Analysis') {
    steps {
        script {
            def scannerHome = tool 'sonar-scanner'
            withSonarQubeEnv('SonarQube') {
                dir('Boardgame-main') {
                    sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=BoardGame \
                        -Dsonar.projectName=BoardGame \
                        -Dsonar.sources=src \
                        -Dsonar.java.binaries=target/classes
                    """
                }
            }
        }
    }
}
    }
}
